[[redirects]]
from="/"
to="/"
status=200

[[redirects]]
from="/signin"
to="/signin"
status=200

[[redirects]]
from="/reset"
to="/reset"
status=200

[[redirects]]
from="/sendemail"
to="/sendemail"
status=200